### ISSUE TITLE
Исправление Readme.

### ISSUE THREAD

**Issue by pavelzarubin** [tri3h/echoBot#1]
Readme недостаточно подробный. Если прописать конфиг и сделать `stack run` проект не запустится.
Лучше в проект класть  шаблон файла конфигурации, с комментариями к каждому полю. И желательно класть в отдельную директорию, чтобы он не терялся.

**Comment by tri3h** [comment]
Я попробовала пару раз клонировать проект в другую папку, заполнить конфиг и stack run, у меня бот запускается. Не могу понять, что я упускаю?

**Comment by pavelzarubin** [comment]
Ну у меня на убунту стак стоял, но я им ни разу не пользовался. Мне нужно было сказать стаку чтоб он компилятор подтянул. Для этого нужно сначала ```stack setup``` использовать.
