### ISSUE TITLE
Настройки сообщества

### ISSUE THREAD

**Issue by AKitavtsev** [tri3h/echoBot#36]
Работа VK  бота зависит от настроек сообщества. В частности от разрешения или запрета типов событий Long Poll API. И по хорошему, при старте бота надо бы произвести эти настройка программно. API 'это позволяет

**Comment by AKitavtsev** [comment]
Хорошо. Но, у меня есть сомнения. Ты устанавливаешь только два события в настройках. А не могут ли другие события оказаться разрешенными, ты их программно не переустанавливаешь. А в результате они помешают работе бота? Проверь это, пожалуйста.

**Comment by AKitavtsev** [comment]
Последнее замечание. Ты пушишь файл конфига. Это плохая практика, можно  случайно запушить токен, а это делать нельзя. Необходимо файл конфига указать в .gitignore. А для пользователя создать шаблон, который называется примерно так: bot.config.template. И в документации указать, что этот файл должен быть переименован и заполнен

**Comment by tri3h** [comment]
> Хорошо. Но, у меня есть сомнения. Ты устанавливаешь только два события в настройках. А не могут ли другие события оказаться разрешенными, ты их программно не переустанавливаешь. А в результате они помешают работе бота? Проверь это, пожалуйста.

Я попробовала включить другие типы событий, бот получает извещения о них, но никак не отвечает на них, только на входящие сообщения. Наверное, так получается, потому что только во входящих сообщениях есть объект "message", и он в боте у меня в instance FromJSON обязательный
